In [1]:
import numpy as np

In [2]:
np.random.rand(2,4)

array([[0.17449912, 0.57196238, 0.97346801, 0.46099616],
       [0.28479777, 0.30183257, 0.16590732, 0.56296012]])

np.ransom.randn(2,3)

In [4]:
np.random.randn(2,3)

array([[-0.2182806 , -0.49921199,  0.93068603],
       [-0.32608129,  0.12465793,  1.43963629]])

In [5]:
np.random.randint(1,100,5)

array([46,  4, 76, 81, 62])

In [6]:
np.random.randint(4,6)

4

In [7]:
np.random.randint(1,50,100)

array([30, 42, 29, 34, 19, 26, 11, 15, 48, 47, 10, 23, 29, 42, 32, 48, 35,
       34, 46, 36,  8, 35, 23,  2, 45,  6,  5, 35, 24,  1,  1, 22, 14, 40,
       31,  1,  7, 16, 35, 38,  7, 11, 12, 11, 47, 28, 35, 47, 27, 29, 13,
       27, 19, 28, 19, 41, 12, 33, 37,  2, 24, 18, 11, 24, 14,  8, 26, 24,
       35, 17, 45,  9, 30, 22, 15, 47, 21, 35, 10, 24, 35, 16, 17, 14, 34,
       26, 14, 11, 26, 27, 23, 34,  7, 18, 46,  7, 26, 40,  3, 20])

In [8]:
array_1 = np.arrange(40)
array_1

AttributeError: module 'numpy' has no attribute 'arrange'

In [9]:
array_1 = np.arange(40)
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [13]:
rand_array = np.random.randint(0,100,20)
rand_array

array([20, 91, 74, 44, 71, 25,  6,  7, 26, 11, 46, 33, 17, 40, 82,  3, 26,
       88, 96, 27])

In [11]:
rand_array

array([], shape=(0, 100, 20), dtype=float64)

In [14]:
array_1.reshape(4,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [16]:
rand_array.min()

3

In [17]:
rand_array.argmin()

15

In [18]:
array_1.dtype

dtype('int32')

In [19]:
a = eye(5)

NameError: name 'eye' is not defined

In [20]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
a.t

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [22]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
b = np.random.rand(2,3)
b

array([[0.04152097, 0.50766508, 0.95147495],
       [0.29924848, 0.57879464, 0.77155951]])

In [27]:
b.T

array([[0.04152097, 0.29924848],
       [0.50766508, 0.57879464],
       [0.95147495, 0.77155951]])

In [28]:
array_2 = np.arange(2,20)

In [29]:
array_2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [30]:
array_2[3]

5

In [31]:
array_2[3:7]

array([5, 6, 7, 8])

In [33]:
array_2[3:6] = 100

In [34]:
array_2

array([  2,   3,   4, 100, 100, 100,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19])

In [35]:
array_2[:] = 1001

In [36]:
array_2

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [37]:
subset = array_2[2:7]
subset

array([1001, 1001, 1001, 1001, 1001])

# Two Dimentional array

In [1]:
import numpy as np

In [4]:
matrix_1 = np.array(([5,10,15,20], [2,4,6,8], [3,6,9,12]))
matrix_1

array([[ 5, 10, 15, 20],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [5]:
matrix_1[0][2]

15

In [6]:
matrix_1[2][:]

array([ 3,  6,  9, 12])

In [7]:
matrix_1[2]

array([ 3,  6,  9, 12])

In [9]:
matrix_1[:,(3,2)]

array([[20, 15],
       [ 8,  6],
       [12,  9]])

# Selection Techniques

In [13]:
array_3 = np.arange(1,21)
array_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
array_3 + array_3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [15]:
np.exp(array_3)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [16]:
np.sqrt(array_3)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [17]:
np.log(array_3)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])

In [18]:
np.max(array_3)

20

In [19]:
np.argmax(array_3)

19

In [20]:
np.min(array_3
    )

1

In [21]:
np.argmin(array_3)

0

In [22]:
np.std(array_3)

5.766281297335398

### std is standard deviation

In [23]:
np.var(array_3)

33.25

### var is variance

In [24]:
np.mean(array_3)

10.5

In [25]:
array_4 = np.random.randn(3,4)

In [26]:
array_4

array([[-1.09749554,  0.80041675, -0.17714396, -0.78389101],
       [-0.17578636,  0.08051149,  2.22896273, -0.9142192 ],
       [-0.35520521,  0.34393364, -0.15174471, -0.06013248]])

In [28]:
np.round(array_4, decimals= 4)

array([[-1.0975,  0.8004, -0.1771, -0.7839],
       [-0.1758,  0.0805,  2.229 , -0.9142],
       [-0.3552,  0.3439, -0.1517, -0.0601]])

In [29]:
array_5 = np.array(["a", "b", "a", "c", "e", "d", "d"])
array_5

array(['a', 'b', 'a', 'c', 'e', 'd', 'd'], dtype='<U1')

In [30]:
np.unique(array_5)

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

### u1 is max charecters is 1

# pandas

### pandas for crasting data , tables , manipulation

In [34]:
import pandas as  pd
import numpy as np

In [36]:
lables = ["a" , "b" , "c" , "d"]
list_3 = [10, 20, 30, 40]
array = np.array([3, 6, 9, 12])
dict_2 = {"a":30, "b":50, "c":60, "d":40}

In [37]:
pd.Series(data = list_3)

0    10
1    20
2    30
3    40
dtype: int64

In [39]:
pd.Series(data=list_3, index=lables)

a    10
b    20
c    30
d    40
dtype: int64

In [40]:
pd.Series(list_3,lables)

a    10
b    20
c    30
d    40
dtype: int64

In [41]:
pd.Series(dict_2)

a    30
b    50
c    60
d    40
dtype: int64

In [50]:
series_1=pd.Series([5, 4, 15, 12], ["respect", "power", "banana", "BANANA"])

In [48]:
series_2 = pd.Series([1, 11, 7, 69], ["respect", "power", "banana", "BANANA"])
series_2

respect     1
power      11
banana      7
BANANA     69
dtype: int64

In [51]:
series_1+series_2

respect     6
power      15
banana     22
BANANA     81
dtype: int64

In [53]:
series_3=pd.Series([5, 4, 15, 12], ["respect", "power", "banana", "BANANASS"])
series_2 = pd.Series([1, 11, 7, 69], ["respect", "power", "banana", "BANANA"])
series_3 + series_2

BANANA       NaN
BANANASS     NaN
banana      22.0
power       15.0
respect      6.0
dtype: float64

In [57]:
df1 = pd.DataFrame(np.random.rand(7,4), index = '1 2 3 4 5 6 7'.split(), columns = 'a b c d'.split())
df1                   

a         b         c         d
1  0.898551  0.474434  0.296290  0.657400
2  0.257160  0.474340  0.759609  0.754164
3  0.359271  0.987330  0.529650  0.926799
4  0.844878  0.417166  0.151852  0.025748
5  0.803400  0.363752  0.330169  0.615782
6  0.430712  0.470171  0.591181  0.784372
7  0.617150  0.170228  0.928724  0.835020

In [60]:
df1["b"]

1    0.474434
2    0.474340
3    0.987330
4    0.417166
5    0.363752
6    0.470171
7    0.170228
Name: b, dtype: float64

In [62]:
df1[["b", "c", "d"]]

b         c         d
1  0.474434  0.296290  0.657400
2  0.474340  0.759609  0.754164
3  0.987330  0.529650  0.926799
4  0.417166  0.151852  0.025748
5  0.363752  0.330169  0.615782
6  0.470171  0.591181  0.784372
7  0.170228  0.928724  0.835020

In [63]:
df1["e"] = df1["a"] + df1["c"]

In [64]:
df1["e"]

1    1.194842
2    1.016769
3    0.888921
4    0.996731
5    1.133569
6    1.021893
7    1.545875
Name: e, dtype: float64

In [65]:
df1

a         b         c         d         e
1  0.898551  0.474434  0.296290  0.657400  1.194842
2  0.257160  0.474340  0.759609  0.754164  1.016769
3  0.359271  0.987330  0.529650  0.926799  0.888921
4  0.844878  0.417166  0.151852  0.025748  0.996731
5  0.803400  0.363752  0.330169  0.615782  1.133569
6  0.430712  0.470171  0.591181  0.784372  1.021893
7  0.617150  0.170228  0.928724  0.835020  1.545875

In [73]:
import pandas as nd
import numpy as np

In [76]:
df2 = {"s.no":['1', '2', '3', '4', '5', '6'], "Name":["black", "red", "blue", "green", "yellow", "white"]}
df = nd.DataFrame(df2)

In [77]:
df

s.no    Name
0    1   black
1    2     red
2    3    blue
3    4   green
4    5  yellow
5    6   white

In [78]:
df.drop(2)

s.no    Name
0    1   black
1    2     red
3    4   green
4    5  yellow
5    6   white

In [85]:
df.drop('s.no', axis=1)

Name
0   black
1     red
2    blue
3   green
4  yellow
5   white

In [80]:
df3 = nd.DataFrame("s.no":['1', '2', '3', '4', '5', '6'], "Name":["black", "red", "blue", "green", "yellow", "white"])
df3

SyntaxError: invalid syntax (491601179.py, line 1)

## How to import dataset using pandas

In [86]:
import numpy as np
import pandas as nd

In [88]:
df = pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Financial-Analytics-Loan-Approval-Prediction/main/loan_prediction.csv")

In [89]:
df.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [90]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [91]:
df.tail()

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [92]:
df.tail(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not Graduate            No   
608  LP002974    Male     Yes          0      Graduate            No   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
604            12000                0.0       496.0             360.0   
605             2400             3800.0         NaN             180.0   
606             3400             2500.0       173.0             360.0   
607             3987             1411.0       157.0             360.0   
608             3232             1950.0       108.0             360.0   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
604             1.0     Semiurban           Y  
605             1.0         Urban           N  
606             1.0     Semiurban           Y  
607             1.0         Rural           Y  
608             1.0         Rural           Y  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [93]:
df.sample()

Loan_ID Gender Married Dependents Education Self_Employed  \
603  LP002958   Male      No          0  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
603             3676             4301.0       172.0             360.0   

     Credit_History Property_Area Loan_Status  
603             1.0         Rural           Y

In [94]:
df.sample()

Loan_ID Gender Married Dependents Education Self_Employed  \
366  LP002187   Male      No          0  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
366             2500                0.0        96.0             480.0   

     Credit_History Property_Area Loan_Status  
366             1.0     Semiurban           N

In [95]:
df.sample()

Loan_ID  Gender Married Dependents Education Self_Employed  \
500  LP002603  Female      No          0  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
500              645             3683.0       113.0             480.0   

     Credit_History Property_Area Loan_Status  
500             1.0         Rural           Y

In [96]:
df.sample(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
587  LP002917  Female      No          0  Not Graduate            No   
337  LP002112    Male     Yes          2      Graduate           Yes   
160  LP001560    Male     Yes          0  Not Graduate            No   
113  LP001392  Female      No          1      Graduate           Yes   
289  LP001935    Male      No          0      Graduate            No   
235  LP001784    Male     Yes          1      Graduate            No   
46   LP001138    Male     Yes          1      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
173  LP001594    Male     Yes          0      Graduate            No   
308  LP001996    Male      No          0      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
587             2165                0.0        70.0             360.0   
337             2500             4600.0       176.0             360.0   
160             1863             1041.0        98.0             360.0   
113             7451                0.0         NaN             360.0   
289             9508                0.0       187.0             360.0   
235             5500             1260.0       170.0             360.0   
46              5649                0.0        44.0             360.0   
610             4106                0.0        40.0             180.0   
173             5708             5625.0       187.0             360.0   
308            20233                0.0       480.0             360.0   

     Credit_History Property_Area Loan_Status  
587             1.0     Semiurban           Y  
337             1.0         Rural           Y  
160             1.0     Semiurban           Y  
113             1.0     Semiurban           Y  
289             1.0         Rural           Y  
235             1.0         Rural           Y  
46              1.0         Urban           Y  
610             1.0         Rural           Y  
173             1.0     Semiurban           Y  
308             1.0         Rural           N

In [100]:
df.shape

(614, 13)

In [101]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [103]:
df.info(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [104]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [105]:
df.info

<bound method DataFrame.info of       Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849          