### lists are data seperated by commas enclosed in suare brackets
### allows multiple data types (heterogenous)

In [1]:
list_1 = [1, 13, "there" ,21]
list_1

[1, 13, 'there', 21]

### index starts with zero(0)

In [2]:
list_1[0]

1

In [3]:
list_1[2]

'there'

In [4]:
list_1[1]
list_[3]

NameError: name 'list_' is not defined

In [5]:
list_1[20]

IndexError: list index out of range

In [6]:
list_1[-1]

21

In [7]:
list_1[-2]

'there'

In [8]:
list_1[0] = 100
list_1

[100, 13, 'there', 21]

### mutable -> lists are mutable i.e. they can be changed

## Tuple

### paranthesis. also heterogenous. not mutable

In [9]:
tuple_1 = (11, "those", 60, 120)
tuple_1

(11, 'those', 60, 120)

In [10]:
tuple_1[0]
tuple_1[-3]

'those'

In [11]:
tuple_1[0]

11

In [12]:
tuple_1[20]

IndexError: tuple index out of range

In [13]:
tuple_1[0]=100
tuple_1

TypeError: 'tuple' object does not support item assignment

#### square brackets for indexing and slicing

## sets

In [1]:
set_1 = {1,2,3.5, "these", 1, 3.5}
set_1

{1, 2, 3.5, 'these'}

#### Sorted based on first charecter
#### elements are not repeated
#### cannot retrive elements using index
#### can add or remove elements tho

#### set is mutable

In [3]:
set_2 = {20, 4, "sup", 10, 9,"heey",500}
set_2

SyntaxError: invalid syntax (2374788955.py, line 1)

In [4]:
set_2

NameError: name 'set_2' is not defined

In [5]:
set_2 = {20, 4, "sup", 10, 9,"heey",500}
set_2

{10, 20, 4, 500, 9, 'heey', 'sup'}

In [6]:
set_2[0] = 2

TypeError: 'set' object does not support item assignment

In [7]:
set_2[2]

TypeError: 'set' object is not subscriptable

In [8]:
set_2.add(40)

In [9]:
set_2

{10, 20, 4, 40, 500, 9, 'heey', 'sup'}

In [10]:
set_2.remove(40)

In [11]:
set_2

{10, 20, 4, 500, 9, 'heey', 'sup'}

## Dictionary

### key value pair data structure- before colon is key, after colon is value
### key should be unique
### if a key is repeated only latest one is considered
### curly braces

In [12]:
dict_1 = {1:"sup", 2:"there", 3:12, 2:35.5, 4:"integer"}
dict_1

SyntaxError: invalid syntax (1000767209.py, line 1)

In [13]:
dict_1

NameError: name 'dict_1' is not defined

In [14]:
dict_1 ={1:"sup", 2:"there", 3:12, 2:35.5, 4:"integer"}
dict_1

{1: 'sup', 2: 35.5, 3: 12, 4: 'integer'}

In [15]:
dict_1[2]

35.5

### here [] has value of key
### we can retrive value using key
### we cannot retrive key using value
### dictionary is mutable

In [17]:
dict_1[10]= "supp"
dict_1

{1: 'sup', 2: 35.5, 3: 12, 4: 'integer', 10: 'supp'}

In [18]:
dict_1[2]= "haha"
dict_1

{1: 'sup', 2: 'haha', 3: 12, 4: 'integer', 10: 'supp'}

In [19]:
dict_1[-2] = 5
dict_1

{1: 'sup', 2: 'haha', 3: 12, 4: 'integer', 10: 'supp', -2: 5}

# NUMPY

### numbers and python

In [2]:
import numpy as np

### np is the alias i.i we'll just say np istead of numpy now

In [1]:
list_2 = [1,3,5]
np.array(list_2)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
list_2 = [1,3,5]
np.array(list_2)

array([1, 3, 5])

In [5]:
list_3 = [[1,3,5],[2,4,6],[2,3,5,7]], dtype=list
np.array(list_3)

C:\Users\RATAN KUMAR\AppData\Local\Temp\ipykernel_6412\795042145.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(list_3)


array([list([1, 3, 5]), list([2, 4, 6]), list([2, 3, 5, 7])], dtype=object)

In [6]:
list_3 = [[1,3,5],[2,4,6],[2,3,5,7]], dtype=int
np.array(list_3)

SyntaxError: cannot assign to literal (1976667369.py, line 1)

In [7]:
list_3 = [[1,3,5],[2,4,6],[2,3,5,7]], dtype=int
np.array(list_3)

SyntaxError: cannot assign to literal (3708983795.py, line 1)

In [8]:
list_3 = [[1,3,5],[2,4,6],[2,3,5,7]], dtype=object
np.array(list_3)

SyntaxError: cannot assign to literal (980507292.py, line 1)

In [9]:
list_3 = [[1,3,5],[2,4,6],[2,3,5,7]], dtype=list
np.array(list_3)

SyntaxError: cannot assign to literal (1976667369.py, line 1)

In [10]:
list_3 = [[1,3,5],[2,4,6],[2,3,5]]
np.array(list_3)

array([[1, 3, 5],
       [2, 4, 6],
       [2, 3, 5]])

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2-6)

array([], dtype=int32)

In [14]:
np.arange(2,6)

array([2, 3, 4, 5])

In [15]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeroes((2,5))

AttributeError: module 'numpy' has no attribute 'zeroes'

In [18]:
np.zeroes(2,5)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [19]:
np.zero((2,5))

AttributeError: module 'numpy' has no attribute 'zero'

In [20]:
np.zeros(2,5)

TypeError: Cannot interpret '5' as a data type

In [21]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros((2,5)), dtype= int

SyntaxError: cannot assign to function call (3314775329.py, line 1)

In [23]:
np.zeros((2,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
list_3 = [[1,3,5],[2,4,6],[2,3,5,7], dtype=list]
np.array(list_3)

SyntaxError: invalid syntax (809066743.py, line 1)

In [25]:
list_3 = [[1,3,5],[2,4,6],[2,3,5,7]]
np.array((list_3), dtype=list)

array([list([1, 3, 5]), list([2, 4, 6]), list([2, 3, 5, 7])], dtype=object)

In [26]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.arrange(-1.2,5,0.5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [28]:
np.arange(-1.2,5,0.5)

array([-1.2, -0.7, -0.2,  0.3,  0.8,  1.3,  1.8,  2.3,  2.8,  3.3,  3.8,
        4.3,  4.8])

In [29]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
np.linspace(2,20,10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [33]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
np.eye(1)

array([[1.]])

In [35]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [36]:
np.random.rand(2,3)

array([[0.43522788, 0.22457011, 0.93385677],
       [0.71520883, 0.25075387, 0.36843075]])

In [37]:
np.random(2,3)

TypeError: 'module' object is not callable